n = int (input ('Digite um numero'))
n1 = float (input ('Digite a primeira nota'))
n2 = float (input ('Digite a segunda nota'))
m = float (input('Digite agora uma quantidade em metros'))
t = int (input ('Digite um Numero para ver sua tabuada'))
d = float (input('Digite quanto vc quer transformar em dolar'))
l = float (input('QUal a altura da parede?'))
a = float (input('QUal a largura da parede?'))
tinta = int(2)

print ('O sucessor do numero {} eh {}'.format (n, (n+1)))
print ('O antecessor do numero {} eh {}'.format (n, (n-1)))

print ('O dobro do numero {} eh {}'.format (n, (n*2)))
print ('A raiz quadrada de {} eh {}'.format (n, (n**0.5)))
print ('A média das 2 notas eh {}'.format ((n1+n2)/2))
print ('{} Metros são exatamente {} Centimetros e {} Milimetros'.format (m, (m*100), (m*1000)))
print ('A tabuada do numero {} eh:\n {}x1= {}\n {}x2= {}\n {}x3= {}\n {}x4= {}\n {}x5={}\n {}x6={}\n {}x7={}\n {}x8={}\n {}x9={}'. format (t, t, (t*1), t, (t*2), t, (t*3), t, (t*4), t, (t*5), t, (t*6), t, (t*7), t, (t*8), t, (t*9)))
print ('Com R${} vc vai conseguir comprar {} Dollares'.format(d, (d/3.27)))
print ('Sabendo que a area da parede eh {}m², precisaremos de {} litro(s) de tinta'.format((l*a), (l*a)/tinta))