n1 = int (input('Digite um valor'))
n2 = int (input('Digite outro valor'))
s = (n1+n2)
print ('A soma entre {} e {} vale {}' .format(n1, n2, s))

n = input ('digite um valror: ')
print (n.isalnum())
print (n.isnumeric())
print (n.islower())
print (n.isupper())
print (n.isspace())
print (n.isdecimal())

n1 = int (input('Digite um numero'))
n2 = int (input ('Digite outro numero'))
s = (n1+n2)
print ('A soma de {} e {} vale {}' .format (n1, n2, s))